"""add discovery timestamp to fofa table

Revision ID: 4acb54529c8f
Revises: 6016f0144e3c
Create Date: 2026-01-17 14:01:29.331701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4acb54529c8f'
down_revision: Union[str, None] = '6016f0144e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('fofa_discovered_at', sa.DateTime(), nullable=True))
    op.add_column('assets', sa.Column('hunter_discovered_at', sa.DateTime(), nullable=True))
    op.add_column('assets', sa.Column('subfinder_discovered_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('subfinder_assets_tenant_id_task_id_type_value_key'), 'subfinder_assets', type_='unique')
    op.create_unique_constraint('uix_tenant_task_subfinder_asset', 'subfinder_assets', ['tenant_id', 'task_id', 'type', 'value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_tenant_task_subfinder_asset', 'subfinder_assets', type_='unique')
    op.create_unique_constraint(op.f('subfinder_assets_tenant_id_task_id_type_value_key'), 'subfinder_assets', ['tenant_id', 'task_id', 'type', 'value'])
    op.drop_column('assets', 'subfinder_discovered_at')
    op.drop_column('assets', 'hunter_discovered_at')
    op.drop_column('assets', 'fofa_discovered_at')
    # ### end Alembic commands ###
