"""initial migration

Revision ID: 6016f0144e3c
Revises: 
Create Date: 2026-01-17 12:45:14.426158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6016f0144e3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # assettype 枚举已存在，使用 create_type=False 避免重复创建
    op.create_table('subfinder_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DOMAIN', 'SUBDOMAIN', 'IP', 'URL', 'ENDPOINT', name='assettype', create_type=False), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('root_domain', sa.String(length=255), nullable=True),
    sa.Column('discovered_urls', sa.JSON(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'task_id', 'type', 'value', name='uix_tenant_task_subfinder_asset')
    )
    op.create_index(op.f('ix_subfinder_assets_domain'), 'subfinder_assets', ['domain'], unique=False)
    op.create_index(op.f('ix_subfinder_assets_id'), 'subfinder_assets', ['id'], unique=False)
    op.create_index(op.f('ix_subfinder_assets_root_domain'), 'subfinder_assets', ['root_domain'], unique=False)
    op.create_index(op.f('ix_subfinder_assets_task_id'), 'subfinder_assets', ['task_id'], unique=False)
    op.create_index(op.f('ix_subfinder_assets_tenant_id'), 'subfinder_assets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_subfinder_assets_type'), 'subfinder_assets', ['type'], unique=False)
    op.create_index(op.f('ix_subfinder_assets_url'), 'subfinder_assets', ['url'], unique=False)
    op.create_index(op.f('ix_subfinder_assets_value'), 'subfinder_assets', ['value'], unique=False)
    op.add_column('assets', sa.Column('discovered_by', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('source_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'source_urls')
    op.drop_column('assets', 'discovered_by')
    op.drop_index(op.f('ix_subfinder_assets_value'), table_name='subfinder_assets')
    op.drop_index(op.f('ix_subfinder_assets_url'), table_name='subfinder_assets')
    op.drop_index(op.f('ix_subfinder_assets_type'), table_name='subfinder_assets')
    op.drop_index(op.f('ix_subfinder_assets_tenant_id'), table_name='subfinder_assets')
    op.drop_index(op.f('ix_subfinder_assets_task_id'), table_name='subfinder_assets')
    op.drop_index(op.f('ix_subfinder_assets_root_domain'), table_name='subfinder_assets')
    op.drop_index(op.f('ix_subfinder_assets_id'), table_name='subfinder_assets')
    op.drop_index(op.f('ix_subfinder_assets_domain'), table_name='subfinder_assets')
    op.drop_table('subfinder_assets')
    # ### end Alembic commands ###
